# fly.toml app configuration file generated for cardmarket-tracker on 2026-02-25T14:26:28+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'cardmarket-tracker'
primary_region = 'arn'

[build]

[env]
  DB_PATH = '/data/tracker.db'
  NODE_ENV = 'production'

[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[mounts]
  source = 'tracker_data'
  destination = '/data'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
